config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'

  # devise_for :users
  # devise_for :users, :controllers => {
  #   :registrations => 'users/registrations',
  #   :sessions => 'users/sessions',
  #   :passwords => 'users/passwords',
  #   :confirmations => 'users/confirmations'
  #  }

  #  devise_scope :user do
  #    get 'sign_up', to: 'users/registrations#new'
  #    get 'sign_in', to: 'users/sessions#new'
  #    delete 'signout', to: 'users/sessions#destroy'
  #  end

  # Can use devise_for to setup different controller routes for situations like Admins https://www.rubydoc.info/github/plataformatec/devise/ActionDispatch%2FRouting%2FMapper:devise_fo
  devise_for :users, :controllers => {
    :registrations => 'users/registrations',
    :sessions => 'users/sessions',
    :passwords => 'users/passwords',
    :confirmations => 'users/confirmations'
  }

   # devise_scope :user do
   #   get 'sign_up', to: 'devise/registrations#new'
   #   get 'sign_in', to: 'devise/sessions#new'
   #   delete 'signout', to: 'devise/sessions#destroy'
   # end

   devise_scope :user do
     get 'sign_up', to: 'users/registrations#new'
     get 'sign_in', to: 'users/sessions#new'
     delete 'signout', to: 'users/sessions#destroy'
   end


  resources :posts
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/shared/_flash_messages.html.erb
<% if flash[:notice]  || flash[:alert]  %>
<div id="msg-container">
  <% if flash[:notice] %>
    <div class="alert alert-success text-center p-4" id="notice-msg-container">
      <span class="notice text-green-700 text-2xl">
        <%= flash[:notice] %>
      </span>
    </div>
  <% end %>

  <% if flash[:alert] %>
    <div class="alert alert-danger text-center p-4" id="alert-msg-container">
      <span class="alert text-red-700 text-2xl">
        <%= flash[:alert].class == String ? flash[:alert].humanize : flash[:alert].to_sentence %>
      </span>
    </div>
  <% end %>
</div>
<% end %>

<script type="text/javascript">

  function removeFadeOut( el, speed ) {
    var seconds = speed/800;
    el.style.transition = "opacity "+seconds+"s ease";

    el.style.opacity = 0;
    setTimeout(function() {
    el.parentNode.removeChild(el);
    }, speed);
  }

  if (document.body.contains(document.getElementById('msg-container')) ) {
    removeFadeOut(document.getElementById('msg-container'), 4500);
  }
</script>

app/views/shared/_navigation.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <a class="navbar-brand" href="/">Rails 6 Devise Template</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarText" aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarText">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link" aria-current="page" href="/">Home</a>
        </li>
        <li class="nav-item">
          <%= link_to "Posts", posts_path, class:"nav-link" %>
        </li>
      </ul>
      <ul class="navbar-nav mb-2 mb-lg-0 d-flex ">

      <% if !current_user %>
        <li class="nav-item">
          <%= link_to "Sign In", sign_in_path, class:'nav-link' %>
        </li>
        <li class="nav-item">
          <%= link_to "Register", new_user_registration_path, class:'nav-link' %>
        </li>
      <% end %>

      <% if current_user %>
        <li class="nav-item">
          <%= link_to "Sign Out", signout_path, method: :delete, class:"nav-link"  %>
        </li>
        <li class="nav-item">
          <%= link_to 'Account Settings', edit_user_registration_path, class:'nav-link' if user_signed_in?%>
        </li>
      <% end %>

      </ul>
    </div>
  </div>
</nav>